// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
using System;
using System.Linq.Expressions;

namespace FlashMapper.DependancyInjection
{
    internal class FlashMapperBuilderConfigurator<TSource1, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

    internal class FlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination> : IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>
    {
        private readonly IFlashMapperSettingsBuilder modelMapperSettingsBuilder;
        private readonly MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination> mappingExpressionStorage;
        public FlashMapperBuilderConfigurator(IFlashMapperSettingsBuilder modelMapperSettingsBuilder, MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination> mappingExpressionStorage)
        {
            this.modelMapperSettingsBuilder = modelMapperSettingsBuilder;
            this.mappingExpressionStorage = mappingExpressionStorage;
        }

        public IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>> mappingExpression)
        {
            mappingExpressionStorage.MappingExpression = mappingExpression;
            return modelMapperSettingsBuilder;
        }
    }

}