// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace FlashMapper
{
    public interface IBuilder<in TSource1, TDestination>
    {
        TDestination Build(TSource1 source1);
        void MapData(TSource1 source1, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2);
        void MapData(TSource1 source1, TSource2 source2, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, in TSource8, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, in TSource8, in TSource9, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, in TSource8, in TSource9, in TSource10, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, in TSource8, in TSource9, in TSource10, in TSource11, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, in TSource8, in TSource9, in TSource10, in TSource11, in TSource12, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, in TSource8, in TSource9, in TSource10, in TSource11, in TSource12, in TSource13, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TSource13 source13);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TSource13 source13, TDestination destination);
    }

    public interface IBuilder<in TSource1, in TSource2, in TSource3, in TSource4, in TSource5, in TSource6, in TSource7, in TSource8, in TSource9, in TSource10, in TSource11, in TSource12, in TSource13, in TSource14, TDestination>
    {
        TDestination Build(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TSource13 source13, TSource14 source14);
        void MapData(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TSource13 source13, TSource14 source14, TDestination destination);
    }

}