// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
using System;
using System.Linq.Expressions;

namespace FlashMapper.DependancyInjection
{
    public interface IFlashMapperBuilderConfigurator<TSource1, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>> mappingExpression);
    }

    public interface IFlashMapperBuilderConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>
    {
        IFlashMapperSettingsBuilder ConfigureMapping(Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>> mappingExpression);
    }

}