//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;

namespace FlashMapper.DependancyInjection
{
    internal class MappingExpressionStorage<TSource1, TDestination>
    {
        public Expression<Func<TSource1, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>> MappingExpression { get; set; }
        
    }

    internal class MappingExpressionStorage<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>
    {
        public Expression<Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>> MappingExpression { get; set; }
        
    }

}