// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace FlashMapper.MultiSource
{
	public class FlashMapperMultiSourceWrap<TSource1, TSource2>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2)
        {
			Source1 = source1;
			Source2 = source2;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
			Source9 = source9;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
		public TSource9 Source9 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
			Source9 = source9;
			Source10 = source10;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
		public TSource9 Source9 { get; }
		public TSource10 Source10 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
			Source9 = source9;
			Source10 = source10;
			Source11 = source11;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
		public TSource9 Source9 { get; }
		public TSource10 Source10 { get; }
		public TSource11 Source11 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
			Source9 = source9;
			Source10 = source10;
			Source11 = source11;
			Source12 = source12;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
		public TSource9 Source9 { get; }
		public TSource10 Source10 { get; }
		public TSource11 Source11 { get; }
		public TSource12 Source12 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TSource13 source13)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
			Source9 = source9;
			Source10 = source10;
			Source11 = source11;
			Source12 = source12;
			Source13 = source13;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
		public TSource9 Source9 { get; }
		public TSource10 Source10 { get; }
		public TSource11 Source11 { get; }
		public TSource12 Source12 { get; }
		public TSource13 Source13 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TSource13 source13, TSource14 source14)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
			Source9 = source9;
			Source10 = source10;
			Source11 = source11;
			Source12 = source12;
			Source13 = source13;
			Source14 = source14;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
		public TSource9 Source9 { get; }
		public TSource10 Source10 { get; }
		public TSource11 Source11 { get; }
		public TSource12 Source12 { get; }
		public TSource13 Source13 { get; }
		public TSource14 Source14 { get; }
    }

 	public class FlashMapperMultiSourceWrap<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15>
    {
        public FlashMapperMultiSourceWrap(TSource1 source1, TSource2 source2, TSource3 source3, TSource4 source4, TSource5 source5, TSource6 source6, TSource7 source7, TSource8 source8, TSource9 source9, TSource10 source10, TSource11 source11, TSource12 source12, TSource13 source13, TSource14 source14, TSource15 source15)
        {
			Source1 = source1;
			Source2 = source2;
			Source3 = source3;
			Source4 = source4;
			Source5 = source5;
			Source6 = source6;
			Source7 = source7;
			Source8 = source8;
			Source9 = source9;
			Source10 = source10;
			Source11 = source11;
			Source12 = source12;
			Source13 = source13;
			Source14 = source14;
			Source15 = source15;
		}
		
		public TSource1 Source1 { get; }
		public TSource2 Source2 { get; }
		public TSource3 Source3 { get; }
		public TSource4 Source4 { get; }
		public TSource5 Source5 { get; }
		public TSource6 Source6 { get; }
		public TSource7 Source7 { get; }
		public TSource8 Source8 { get; }
		public TSource9 Source9 { get; }
		public TSource10 Source10 { get; }
		public TSource11 Source11 { get; }
		public TSource12 Source12 { get; }
		public TSource13 Source13 { get; }
		public TSource14 Source14 { get; }
		public TSource15 Source15 { get; }
    }

 }
