//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;

namespace FlashMapper.MultiSource
{
	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TSource13, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TSource13, out TSource14, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination> beforeMapCallback);
    }

	public interface IFlashMapperMappingCallbacksBuilder<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TSource13, out TSource14, out TSource15, out TDestination, out TConfigurator> 
        where TConfigurator: IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TDestination, TConfigurator>
    {
        TConfigurator AfterMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TDestination> afterMapCallback);
        TConfigurator BeforeMap(Action<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TDestination> beforeMapCallback);
    }

}