//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;

namespace FlashMapper.MultiSource
{
    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TSource13, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TSource13, out TSource14, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TDestination>>
    {
    }

    public interface IFlashMapperMappingConfigurator<out TSource1, out TSource2, out TSource3, out TSource4, out TSource5, out TSource6, out TSource7, out TSource8, out TSource9, out TSource10, out TSource11, out TSource12, out TSource13, out TSource14, out TSource15, out TDestination> : 
        IFlashMapperSettingsBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TDestination>>,
        IFlashMapperMappingCallbacksBuilder<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TDestination, IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TDestination>>, 
        IFlashMapperCustomServiceBuilder<IFlashMapperMappingConfigurator<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TDestination>>
    {
    }

}